---
- name: Share directories exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0777
    owner: root
    group: wheel
    recurse: yes
  with_items:
    - "{{ nfs_shares }}"
- name: Configure NFS exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify:
  - Restart NFS service
